import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_BROWSERS_PATH ? undefined : '/opt/pw-browsers/chromium' });
const page = await b.newPage({ viewport:{width:390,height:844} });
let payload=null, redirected=false;
await page.route('**/cart/add.js', async r => { payload = r.request().postDataJSON(); await r.fulfill({ status:200, contentType:'application/json', body:'{}' }); });
await page.exposeFunction('noop', ()=>{});
page.on('framenavigated', f => { if(f.url().includes('/checkout')) redirected = true; });
const errs=[]; page.on('pageerror', e=>errs.push(String(e).slice(0,150)));
await page.goto('http://127.0.0.1:8791/smoke.html');
await page.waitForTimeout(1200);
console.log('step1 plans:', await page.evaluate(()=>document.querySelectorAll('#root .plan').length));
console.log('countdown:', await page.evaluate(()=>document.getElementById('cd').textContent));
await page.click('#root .plan[data-n="2"]');
await page.click('#sb-next');
await page.waitForTimeout(400);
console.log('step2 hint:', await page.evaluate(()=>document.getElementById('hint2').innerText));
const adds = await page.$$('#root .pick .add');
await adds[0].click(); await adds[6].click();
await page.waitForTimeout(300);
console.log('sb after 2 picks:', await page.evaluate(()=>document.getElementById('sb-count').textContent+' | '+document.getElementById('sb-next').textContent));
await page.click('#sb-next');
await page.waitForTimeout(500);
const s3 = await page.evaluate(()=>({due:document.getElementById('duetoday').textContent, rows:document.querySelectorAll('#kitcart .krow').length, val:document.getElementById('valline').innerText, meta:document.querySelector('#kitcart .kmeta').textContent, dint:[...document.querySelectorAll('#kitcart .kint')].pop().textContent}));
console.log('step3:', JSON.stringify(s3));
await page.click('#sb-next');
await page.waitForTimeout(1500);
console.log('ATC payload:', JSON.stringify(payload));
console.log('redirect to checkout attempted:', redirected);
console.log('page errors:', errs.length? errs : 'none');
await page.screenshot({path:'smoke-step3.png', fullPage:false});
await b.close();
