import { chromium } from 'playwright';
const b = await chromium.launch();
const page = await b.newPage({ viewport:{width:390,height:844} });
let payload=null;
await page.route('**/cart/add.js', async r => { payload = r.request().postDataJSON(); await r.fulfill({ status:200, contentType:'application/json', body:'{}' }); });
const errs=[]; page.on('pageerror', e=>errs.push(String(e).slice(0,150)));
await page.goto('http://127.0.0.1:8794/smoke.html');
await page.waitForTimeout(900);
console.log('sticky gone:', await page.evaluate(()=>!document.getElementById('sbar')));
console.log('badge on n2:', await page.evaluate(()=>!!document.querySelector('.plan[data-n="2"] .plan-badge') && !document.querySelector('.plan[data-n="3"] .plan-badge')));
await page.click('#root .plan[data-n="2"]');
await page.click('#root #s1 .btn');
await page.waitForTimeout(300);
const adds = await page.$$('#root .pick .add');
await adds[2].click(); await adds[4].click();
console.log('s2sum:', await page.evaluate(()=>document.getElementById('s2sum').textContent));
console.log('s2 next:', await page.evaluate(()=>document.getElementById('sb-next').innerText+' disabled='+document.getElementById('sb-next').disabled));
await page.click('#sb-next');
await page.waitForTimeout(400);
console.log('valline:', await page.evaluate(()=>document.getElementById('valline').innerText));
console.log('hiw3 cells:', await page.evaluate(()=>document.querySelectorAll('.hiw3 .hcell').length+' | '+[...document.querySelectorAll('.hiw3 b')].map(x=>x.textContent).join(', ')));
await page.click('#root #s3 .navrow .btn:not(.secondary)');
await page.waitForTimeout(900);
console.log('payload:', JSON.stringify(payload));
console.log('errors:', errs.length?errs:'none');
await b.close();
